name: yolo-mobile
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.14
  - pip
  - opencv
  - pillow
  - numpy
  - matplotlib
  - pyyaml
  - requests
  - tqdm
  - pytorch
  - torchvision
  - pip:
    - ultralytics>=8.3.179,<9.0.0